Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Name=专家信息
Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Expert.Name=专家信息
Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Expert.ID.Name=ID
Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Expert.expert_name.Name=专家姓名
Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Expert.expert_mobile.Name=专家手机
Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Expert.expert_sex.Name=专家性别
Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Expert.expert_sex.男.DisplayValue=男
Inspur.GS.JCPT.CZ.ZJ.ZJ.Back.Expert.Expert.expert_sex.女.DisplayValue=女
