Inspur.GS.JCPT.CZ.ZJ.ZJ.Front.Vo.ExpertCatalogForm_frm.Name=专家信息表单_frm
Inspur.GS.JCPT.CZ.ZJ.ZJ.Front.Vo.ExpertCatalogForm_frm.Expert.Name=专家信息
Inspur.GS.JCPT.CZ.ZJ.ZJ.Front.Vo.ExpertCatalogList_frm.Name=专家信息列表_frm
Inspur.GS.JCPT.CZ.ZJ.ZJ.Front.Vo.ExpertCatalogList_frm.Expert.Name=专家信息
Inspur.GS.JCPT.CZ.ZJ.ZJ.Front.ExpertCatalogForm.Form.title=专家信息表单
Inspur.GS.JCPT.CZ.ZJ.ZJ.Front.ExpertCatalogList.Form.title=专家信息列表
